version: '2'

services:
  web:
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
        - .:/var/www
        - ./config/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    build: ./config/docker/php
    volumes:
      - .:/var/www
      - ./config/docker/php/20-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    extends:
      file: ./config/docker/envs/develop.yml
      service: php
    links:
       - appdb

  appdb:
    image: mysql:5.7
    ports:
       - "3306:3306"
    volumes:
      - ./mysqldata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=transloadit
      - MYSQL_USER=transloadit
      - MYSQL_PASSWORD=transloadit
